---
- hosts: debian
  become: true
  tasks:
    - name: "Installing curl"
      apt:
        name:
          - curl
          - iperf3
          - htop
          - wget
          - git
      state: present
      update_cache: true
